exports.INVALID_LOGIN_CREDENTIALS = 401;
exports.FIELD_MISSING = 401;
exports.USER_ALREADY_EXISTS = 401;
exports.USER_NOT_FOUND = 400;
exports.INTERNAL_SERVER_ERROR = 500;
exports.INVALID_CREDENTIALS = 401;
exports.CHAT_NOT_FOUND = 400;